server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false

plugins:
  youtube:
    enabled: true
    oauth:
      enabled: true
      refreshToken: ${YOUTUBE_REFRESH_TOKEN}
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - "TV"
      - "TVHTML5EMBEDDED"
      - "WEB"
      - "MWEB"
      - "WEBEMBEDDED"
      - "MUSIC"
      - "ANDROID_VR"
      - "ANDROID_MUSIC"
      - "IOS"
    clientOptions:
      TV:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: false
      TVHTML5EMBEDDED:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: true
      WEB:
        playback: false
        playlistLoading: true
        searching: true
        videoLoading: true
      MWEB:
        playback: false
        playlistLoading: true
        searching: true
        videoLoading: true
      WEBEMBEDDED:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
      MUSIC:
        playback: false
        playlistLoading: false
        searching: true
        videoLoading: false
      ANDROID_VR:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      ANDROID_MUSIC:
        playback: true
        playlistLoading: false
        searching: true
        videoLoading: true
      IOS:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true

  lavalyrics:
    sources:
      - spotify
      - youtube
      - deezer
      - yandexMusic

  lavasrc:
    providers:
      - "scsearch:%QUERY%"
      - 'ytsearch:"%ISRC%"'
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
      youtube: true
      vkmusic: false
      tidal: false
      qobuz: false
      ytdlp: false
      jiosaavn: false
    lyrics-sources:
      spotify: false
      deezer: false
      youtube: false
      yandexmusic: false
      vkmusic: false
      lrcLib: false
    spotify:
      albumLoadLimit: 6
      artistLoadLimit: 6
      clientId: ${SPOTIFY_CLIENT_ID}
      clientSecret: ${SPOTIFY_CLIENT_SECRET}
      countryCode: ${SPOTIFY_COUNTRY_CODE}
      customTokenEndpoint: ${SPOTIFY_CUSTOM_TOKEN_ENDPOINT}
      localFiles: true
      playlistLoadLimit: 6
      preferAnonymousToken: true
      resolveArtistsInSearch: true
      searchLimit: 6
      spDc: ${SPOTIFY_SP_DC}
    applemusic:
      countryCode: ${APPLEMUSIC_COUNTRY_CODE}
      mediaAPIToken: ${APPLEMUSIC_MEDIA_API_TOKEN}
      keyID: ${APPLEMUSIC_KEY_ID}
      teamID: ${APPLEMUSIC_TEAM_ID}
      musicKitKey: |
        ${APPLEMUSIC_MUSICKIT_KEY}
      playlistLoadLimit: 6
      albumLoadLimit: 6
    deezer:
      masterDecryptionKey: ${DEEZER_MASTER_DECRYPTION_KEY}
      arl: ${DEEZER_ARL}
      formats: ["FLAC", "MP3_320", "MP3_256", "MP3_128", "MP3_64", "AAC_64"]
    yandexmusic:
      accessToken: ${YANDEXMUSIC_ACCESS_TOKEN}
      playlistLoadLimit: 1
      albumLoadLimit: 1
      artistLoadLimit: 1
    flowerytts:
      voice: "default voice"
      translate: false
      silence: 0
      speed: 1.0
      audioFormat: "mp3"
    youtube:
      countryCode: "US"
      language: "en"
    vkmusic:
      userToken: ${VKMUSIC_USER_TOKEN}
      playlistLoadLimit: 1
      artistLoadLimit: 1
      recommendationsLoadLimit: 10
    tidal:
      countryCode: ${TIDAL_COUNTRY_CODE}
      searchLimit: 6
      token: ${TIDAL_TOKEN}
    qobuz:
      userOauthToken: ${QOBUZ_USER_OAUTH_TOKEN}
    ytdlp:
      path: "yt-dlp"
      searchLimit: 10
    jiosaavn:
      decryption:
        secretKey: ${JIOSAAVN_SECRET_KEY}

  dunctebot:
    ttsLanguage: "en-US"
    sources:
      getyarn: true
      clypit: true
      tts: true
      pornhub: true
      reddit: true
      ocremix: true
      tiktok: true
      mixcloud: true
      soundgasm: true
      pixeldrain: true

lavalink:
  plugins:
    - dependency: "com.dunctebot:skybot-lavalink-plugin:1.7.0"
      snapshot: false
    - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0"
      snapshot: false
    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:7d60077"
      snapshot: true
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.0"
      snapshot: false
    - dependency: "com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.1"
      snapshot: false
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.5"
      snapshot: false
  pluginsDir: "./plugins"
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    nonAllocatingFrameBuffer: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    youtubeConfig:
      email: ${YOUTUBE_EMAIL}
      password: ${YOUTUBE_PASSWORD}

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENVIRONMENT}

logging:
  file:
    max-history: 5
    max-size: 10MB
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
    com.github.topi314.lavasrc: DEBUG
    lavalink.server.io.SocketContext: OFF
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: OFF
    com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream: OFF
    com.sedmelluq.discord.lavaplayer.source.youtube.YoutubePersistentHttpStream: OFF
    com.github.topi314.lavasrc.LavaSrcTools: OFF
    dev.lavalink.youtube.YoutubeAudioSourceManager: OFF
    dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
